### ISSUE TITLE
"distribute" over Unboxed vector

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear#61] opened 2015-01-25 11:05 UTC
It would be great if there was a way to turn a `Vector (V4 Double)` to a `V4 (Vector Double)`. There is `distribute`, of course, but it only works for `Functor`s, of which `Vector`s are not. Is there a better way than to write a new `VectorDistributive` class?

**Comment by ekmett** [comment] 2015-03-07 08:25
We don't really have much support at all for unboxed stuff in linear.

**Comment by ekmett** [comment] 2015-03-07 08:28
I don't have a better suggestion than to write such a class inline in your codebase if you find yourself needing it.

**Comment by ekmett** [comment] 2015-07-08 16:17
Closing this as, effectively, a duplicate of #17.

**Closed by ekmett** 2015-07-08 16:17 UTC
